### ISSUE TITLE
Collections not loaded

### ISSUE THREAD

**Issue by stefania-santimbrean** [postmanlabs/postman-collection#1254]
Hello,

Is there an issue with Postman collection right now?
![image](https://user-images.githubusercontent.com/74544010/156998838-14998996-6378-4b08-99b0-64e991b6b483.png)

Kind regards,
Stefania

**Comment by codenirvana** [comment]
We are experiencing some downtime due to a connectivity issue with one of our storage systems.
We are currently working on resolving it.

Please follow our status page for updates: https://status.postman.com/

---

Closing because this issue is already reported here: https://github.com/postmanlabs/postman-app-support/issues/10729
