### ISSUE TITLE
Postman collection not working with Newman 3.2.0

### ISSUE THREAD

**Issue by shruti2591** [postmanlabs/postman-collection#199]
Hi Team,

With the latest release of Newman(from version 1.3 to 3.2 ), the postman scripts are not working with Newman.
We are getting the below error :
ReferenceErr $ is not defined.

PFA sample script created for this.
Can you please provide your inputs, as this was working fine with the old Newman version.
[Test.postman_collection.zip](https://github.com/postmanlabs/postman-collection/files/578825/Test.postman_collection.zip)

**Comment by czardoz** [comment]
Hi Shruti,

Since Newman v3.0, we've deprecated support for jQuery in the testing sandbox, in order to provide a consistent experience to users across the native Postman apps and Newman. Support for jQuery in Postman Chrome will soon be removed too. 

We've added a similar library called "cheerio" in the sandbox which will help you to run assertions on HTML responses: https://cheerio.js.org

⁣You'll be able to use cheerio directly in the sandbox, without having to require it: https://www.getpostman.com/docs/sandbox

Hope this helps :)

Sent from BlueMail

​
