### ISSUE TITLE
postman json prompt problem

### ISSUE THREAD

**Issue by hgfgood** [postmanlabs/postman-collection#58]
when i wrote json  http body, it has prompt,I'm happy, but there exist a small problem。If there is a JSONArray in the json String, it will prompt error like this:
![ problem](http://i1.piimg.com/4851/93d03db433ce21d7.jpg)

However, the json String is absolutely right.

**Comment by czardoz** [comment]
Hi,

This repository is present for issues related to the Postman SDK. The correct place for support issues is: https://github.com/postmanlabs/postman-app-support/issues, do use that next time :smile: .

The json string is not right, because JSON does not allow having single quotes (`'`). You must use double quotes (`"`) in all your strings.

**Comment by hgfgood** [comment]
You are right. Thank you!
