### ISSUE TITLE
Allow running collections concurrently

### ISSUE THREAD

**Issue by leonklingele** [postmanlabs/postman-collection#790]
It would be great to allow running requests inside a collection concurrently.
This allows to detect race conditions in Go services more easily.

**Comment by codenirvana** [comment]
@leonklingele Thanks for the feature request. But this repository is specific to Postman Collection SDK library. We track all the issues/feature requests here: https://github.com/postmanlabs/postman-app-support/issues

You can use Newman for parallel collection runs: https://github.com/postmanlabs/newman/blob/develop/examples/parallel-collection-runs.js
But, running requests in a collection concurrently is something we will consider while building  APIs using a new DSL: https://github.com/postmanlabs/postman-app-support/issues/5707#issuecomment-450947474

I am closing this issue here, can you create a new issue with your detailed use case in our issue tracker?
